name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run test
      env:
        CI: true

  npm-install:
    name: Live testing the npm package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Making a sample Javascript project
      run: |
        echo -e "const { getShipById, updateShipsData } = require('@azurapi/azurapi');\nvar testShip = getShipById(140);\nif (!testShip) process.exit(1);\nif (testShip.names.en !== 'Hermes') process.exit(1);" >> sample.js
        npm i @azurapi/azurapi @babel/cli @babel/core @babel/preset-env babel-jest jest request jsdom srcset
        node sample.js