name: Github Actions

on: [push]

jobs:
  jest:
    name: Running Jest tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, compile, and test
      run: |
        npm install
        npm run compile
        npm run test
      env:
        CI: true
    - name: codecov
      run: |
        npm install codecov nyc
        codecov
        nyc report --reporter=json > coverage/coverage.json