name: Github Actions

on: [push]

jobs:
  jest:
    name: Running Jest tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps: 
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, compile, and test
      run: |
        npm install
        npm run compile
        npm run test
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: AzurAPI Pre-Release
        path: /home/runner/work/azurapi-js/azurapi-js/build/*
      env:
        CI: true
