name: npm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Making a sample Javascript project
      run: |
        echo -e "const { getShipById, updateShipsData } = require('@azurapi/azurapi');\nconsole.log(getShipById(140));" >> sample.js
        npm i @azurapi/azurapi @babel/cli @babel/core @babel/preset-env babel-jest jest request jsdom srcset
        node sample.js